est_strings = [
'Eddie ülevaatuspunkt',
'Hiina tänava draakoni pood',
'klaasilõikur-1',
'Pärnu autoparandus',
'klaasilõikur-2',
'Juveelipood (Seif)',
'Pärnu eramajade juures olev punker',
'Deemand Väike',
'[DEBUG] award_in_game_cash send_game_hint result -> {result}',
'Postal code {postal_code}',
'Toiming ebaõnnestus: sa lahkusid asukohast enne protsessi lõppu.',
'🚨 Signaaliblokker ebaõnnestus — alarm läks käima 🚨',
'✅ Signaaliblokker toimis — alarm ei aktiveerunud ✅',
'Keegi teatas, et {location_name} juures toimub kahtlane tegevus.',
'Uhoh... Lekitatud info: keegi nägi sind {location_name} juures ja helistas politseisse!',
'Hei! Boss ütleb, et politsei raadio tundub vaikne ja kaamerad võivad olla maas. Tegutse kiiresti!',
'Asukoht: Haapsalu vana tsiviilspawn. (11042)',
'Heist ebaõnnestus: sa lahkusid piirkonnast enne, kui raha oli tasku pistetud. Proovi uuesti hiljem.',
"Rööv: {location_data['label']}",
'Heist Info sessioon on möödas või aegunud.',
'Mine elektroonikapoodi.\\nZIP: 403\\nPalun leia õige asukoht, kus sa pead olema.',
'Mitte õnnestunud: sa ei jõudnud elektroonikapoodi 5 minuti jooksul.',
'Kas sa tahad osta signaaliblokkerit 25 000 eest? (Kestab 5 sekundit)',
'Okei, sa ei soovi osta. Head aega.',
'Signaali blokkeri krediitkaardi ostmine ebaõnnestus: {update_message}',
'Te maksite krediitkaardiga 25 000. Raha võetakse ära ja te võite jääda miinustesse. Signaali blokker lisatud sinu inventari.',
'Te maksite krediitkaardiga 25 000, kuid signaali blokkeri lisamine inventari ebaõnnestus: {message}',
'Okei, sa ei soovi krediitkaardiga maksta. Head aega.',
'BOAT API pole konfigureeritud, ei saa osta.',
'Mügimees ütles, et teie kaardil pole piisavalt vahendeid.',
'Selletõttu, et teil pole piisavalt vahendeid, kas te soovite krediitkaardiga maksta? (Raha võetakse ära ja võite jääda miinustesse)',
'Signaali blokkeri ostmine ebaõnnestus: {update_message}',
'Signaali blokker lisatud sinu inventari.',
'Signaali blokker osteti, kuid lisamine inventari ebaõnnestus: {message}',
'Sul on juba aktiivne HeistInfo sessioon. Oota, kuni see lõpeb.',
'Vali õige heistiga koht: Juveelid või Pank.',
"Sõida ZIP {heist_location['zip']}, {heist_location['label'].split(' (')[0]}",
"Sõida asukohta: {heist_location['label']}",
'Ebaõnnetus: sa ei jõudnud valitud asukohta 5 minuti jooksul.',
'Sa uurid järgmised 5 sekundit ümbrust.',
'Sa lahkusid asukohast enne 5 sekundi möödumist. Proovi uuesti.',
'Hmm.. Tundub, et siin on turvakaamerad.\\nBoss soovitab signaaliblokkerit.\\nKas sa soovid seda?',
'Invalid heist selection.',
'Sul on juba aktiivne heist. Vali oma tööriist selle heisti jaoks.',
'Mine {heist_data["label"]} ZIP {heist_data["zip"]} juurde.\\n',
'Sul on 5 minutit, et sinna jõuda.',
'Ei õnnestunud: sa ei jõudnud asukohta õigeaegselt.',
'Heist sessioon kadus enne kui jõudsid kohale.',
'Okei. Enne kui sa pääsed seifini sa pead saama turvavärava lahti. ',
'Okei, sa oled nüüd kohal. Nüüd on sinu otsustada, mida sa järgmisena kasutad.',
'Sa oled juba tööriista valinud. Oota, kuni protsess lõpeb.',
'Heist sessioon ei ole enam aktiivne.',
'Inventuuri kontroll ebaõnnestus: {error}',
'Sul pole inventaris tööriista {item_name}.',
'Inventuuri uuendamine ebaõnnestus: {remove_error}',
'Sa tegutsed... ⏳',
'Okei, tubli. Sa oled seifi juures. Millega sa seifi lahti teed?',
'Heist lõpetatud, kuid esemete lisamine ebaõnnestus: {boat_message}',
'Ai. Tundub, et rahaauto oli vahepeal raha ära viinud. Ei vea... Sa võtsid mida sa said.',
'Heist lõpetatud, kuid mustaraha lisamine ebaõnnestus: {message}',
'Boss kutsus sind tauniks. Seif on tehtud metallist, mitte klaasist. ',
'Tõmba sealt kiiresti minema, alarm käivitus ja politsei on teel!',
'Okei. Hea valik, sa said peaaegu kõik rahatähed endale. ',
'Laser oli võimas ja kõrvetas paar tähte tuhaks. ',
'Sa lugesid kokku: {amount} mustaraha.',
'Oi oi... Pomm lasi enamus raha õhku... ',
'Uhoh. Sinu pomm oli halvasti ehitatud ja see plahvatas koheselt.\\n',
'Su heist kukus läbi.',
'Uhoh. Sinu pomm plahvatas, kuid mõned tapmiskäsud ebaõnnestusid:\\n',
'Uhoh. Sinu pomm oli halvasti ehitatud ja see plahvatas koheselt, kuid piirkonnas ei leitud mingeid mängijaid.\\n',
'Sa asetasid pommi väravale. Värav lendas õhku ja pääsesid seifi juurde.',
'--Sa lõikad laseriga luku maha--',
'Boss kutsus sind tauniks. Väravad ei ole klaasist tehtud. ',
'Tõmba nüüd kiiresti minekut. Sa kukkusid läbi. Pead uuesti proovima.',
'Pank värav',
'Sa kukkusid läbi. Pead uuesti proovima.',
'Pomm purustas kõik deemandid. Sa ei saanud midagi.',
'Sa lõikad seifi... ⏳ (5 sekundit)',
'Heist ebaõnnestus: sa lahkusid seifi piirkonnast.',
'Sa kogud teemante... ⏳ (5 sekundit)',
'Sa läksid seifi kallale. Sa said: ',
'Seif on avanenud. Kogud raha... ⏳ (5 sekundit)',
'Sinu käed värisesid lõikamise ajal ja osa rahast kõrbes. ',
'Sa said kokku {amount} mustaraha.',
'Sa lõikad lahti ja saad kokku {amount} mustaraha.',
'Heist ebaõnnestus: sa lahkusid enne pommi aktiveerumist.',
'Pomm purustas suure osa rahatähtedest! ',
'Sa leidsid ainult {amount} mustaraha alles.',
'Seif avanes ja sa kogusid kokku {amount} mustaraha.',
'Sa töötled seifi... ⏳',
'Sa ei leidnud deemandeid.',
'Boss kutsus sind tauniks. Seif ei ole klaasist tehtud. Tõmba minekut.',
'Seif ei avanud. Alarm käivitub.',
'Sa lõikad ust laseriga... ⏳ (5 sekundit)',
'Uks on avanenud. Kogud raha... ⏳ (5 sekundit)',
'Sa lõikad ust laseriga ja pääsed seifi juurde. ',
'Sa saad {amount} mustaraha.',
'Tundub, et uks on paksem kui laser suudab lõigata.',
'Laser ei läbinud ust. Alarm käivitub.',
'Seif on avanenud. Nüüd on sul 5 sekundit aega raha kokku koguda. ⏳',
'Nüüd kogusid raha kokku 5 sekundi jooksul. Alarm käivitub.\\n',
'Paigaldad Pommi... ⏳ (5 sekundit)',
'Test õnnestus!',
'Vihje saatmine ebaõnnestus: {result["error"]}',
'Vihje saadetud: {hint_command}',
'Vihje saadetud: :h testvihje',
'Vihje saatmine ebaõnnestus: testviga',
'Starting challenge: Prepstart — Eddie ülevaatuspunkt',
'Väljakutse: Pomm\\nMine Eddie ülevaatuspunkt asukohaga ZIP 501. Ole seal 5 sekundit.',
'Sa jõudsid Eddie ülevaatuspunkt. Oota 5 sekundit kohalolekut.',
'Sa valmistad pommi järgmised 5 sekundit.',
'Sa lahkusid piirkonnast enne nõutud aja möödumist. Väljakutse ebaõnnestus.',
'Okei, tubli! Sa said vajaliku asja kätte. Tõmba nüüd kiiresti minema, et keegi ei märkaks.',
'Mine Pank ZIP 123 juurde. Sul on 5 minutit, et sinna jõuda.',
'Rahapesu algab 1000 suuruse summaga. Oota 5 sekundit...',
'Rahapesu ebaõnnestus: sa lahkusid pesumaja piirkonnast.',
'Oled pesumajas. Vajuta nuppu "Pese raha", et valida summa ja alustada rahapesu.',
'Oled punkris. Kui oled valmis, vali deemand mida sa müüa tahad ja sisesta kogus.',
'Piirkonnas 2051 Freedom Avenue ei leitud mingeid mängijaid.',
'Tapetud mängijad: hannahplay21',
'Tapmine ebaõnnestus: error',
'Uuups... Lekkinud info: keegi nägi sind Pank juures ja helistas politseisse!',
'Hei! Boss ütleb, et politsei radar näib vaikne ja kaamerad võivad olla häiritud. Toimi kiiresti!',
'See on testipopup, mille kaudu saab näha, kuidas info kanalisse jõuab.',
'Näidisembed:',
'Väljakutse: {challenge_data["display_name"]}\\n',
'Mine {mission_data["name"]} asukohaga ZIP {mission_data["zip"]}',
'Ebaõnnestus: sa ei jõudnud sihtkohta 5 minuti jooksul.',
'Sa jõudsid {mission_data["name"]}. Oota {mission_data["required_stay_sec"]} sekundit kohalolekut.',
"<@{NOTIFY_DISCORD_ID}> {challenge_data['reward']} lõpetatud mängijalt {username}!\\n",
'VALMISTAMINE LÄBI\\n',
'Roboxi mängija: {username}\\n',
'Alarm: {alarm_status}',
'Õnnestus! {challenge_data["reward"]} valmis, kuid BOAT inventari uuendamine ebaõnnestus: {boat_message}',
'Ei õnnestunud saada asukohta mängijale {username}: {error_text}',
'Asukoht mängijale {username}:\\n```json\\n{format_player_location(player_data)}\\n```',
'Pärnus tegutseb tundmatu müügimees.\\n',
'Jutud käivad, et tema müügikoht asub {DEEMAND_SELL_LOCATION["label"]} ({DEEMAND_SELL_LOCATION["zip"]})\\n',
'Sa ei jõudnud punkrisse 5 minuti jooksul, müügimees läks enne koju ära.',
'Jutud käivad, et tema müügikoht asub 301 läheduses.\\n',
'Lisainfo: Mine lähedale koordinaatidele {LAUNDROMAT_LOCATION["x"]}, {LAUNDROMAT_LOCATION["z"]} (mitte täpselt, vaid ümberringi).',
'Sul on juba aktiivne rahapesu. Oota, kuni see lõpeb enne uue käivitamist.',
'Hmmm... Sul on raha must?\\n',
'Ma tean ühte kohta.\\n',
'Mine 301 lähedusse.\\n',
'Asukoht: {LAUNDROMAT_LOCATION["x"]}, {LAUNDROMAT_LOCATION["z"]}.\\n',
'Mitte õnnestunud: sa ei jõudnud 301 lähedusse 5 minuti jooksul.',
'Rahapesu käivitus ebaõnnestus: {exc}',
'Rahapesu on juba pooleli. Oota, kuni see lõpeb.',
'Rahapesu algab {amount} suuruse summaga. Oota 5 sekundit...',
'Sul pole piisavalt mustraha. Vajad vähemalt {amount} mustraha, et seda rahapesu käivitada.',
'Mustraha eemaldamine ebaõnnestus: {remove_error}',
'\n    try:\n        result = await erlc_client.send_game_hint(',
', hint_command)\n        if isinstance(result, dict) and result.get(',
', kill_command)\n        if isinstance(result, dict) and result.get(',
'\n        try:\n            result = await erlc_client.send_game_hint(',
', kill_command)\n            if isinstance(result, dict) and result.get('
]
